dotrain: true
doapply: true
doplot: true
dogrid: false
dobayes: false
doprofile: false
docreatendvaldata: false
docreatepdfmaps: false
docreatepdfmapforvariable: false
docreatepdfmapformeanid: false
domergepdfmaps: false
