case: DNN_fluctuations
dotrain: true
doapply: false
doplot: false
dogrid: false
doprofile: false
docreatevaldata: false
docreatepdfmaps: false
docreatepdfmapforvariable: false
docreatepdfmapformeanid: false
domergepdfmaps: false
