dotrain: true
doapply: true
doplot: true
dogrid: false
dobayes: false
doprofile: false
docreatevaldata: true
docreatepdfmaps: false
docreatepdfmapforvariable: false
docreatepdfmapformeanid: false
domergepdfmaps: false
